{
 "title": "Inference-Server-Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GPU Bytes Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_gpu_memory_used_bytes{job=\"triton_server\"}/nv_gpu_memory_total_bytes{job=\"triton_server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nv_gpu_utilization{job=\"triton_server\"}"
    }
   ]
  },
  {
   "title": "Input time / req",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(irate(nv_inference_compute_input_duration_us{job=\"triton_server\"}[$__rate_interval]) / 1000) / irate(nv_inference_request_success{job=\"triton_server\"}[$__rate_interval])",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Inference time / req",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "(irate(nv_inference_compute_infer_duration_us{job=\"triton_server\"}[$__rate_interval]) / 1000) / irate(nv_inference_request_success{job=\"triton_server\"}[$__rate_interval])",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Output time / req",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(irate(nv_inference_compute_output_duration_us{job=\"triton_server\"}[$__rate_interval]) / 1000)/ irate(nv_inference_request_success{job=\"triton_server\"}[$__rate_interval])",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "DB ratio ( #request / #exec )",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (model,version) (rate(nv_inference_request_success{job=\"triton_server\"}[$__rate_interval])/rate(nv_inference_exec_count{job=\"triton_server\"}[$__rate_interval]) )",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Batchsize ( #infer/ #exec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (model,version) (rate(nv_inference_count{job=\"triton_server\"}[$__rate_interval])/rate(nv_inference_exec_count{job=\"triton_server\"}[$__rate_interval]) )",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Infer/Input/Output Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "rate(nv_inference_compute_infer_duration_us{job=\"triton_server\"}[$__interval]) / 1000",
     "legendFormat": "{{model}}InferDur"
    },
    {
     "expr": "rate(nv_inference_compute_input_duration_us{job=\"triton_server\"}[$__interval]) / 1000",
     "legendFormat": "{{model}}InputDur"
    },
    {
     "expr": "rate(nv_inference_compute_output_duration_us{job=\"triton_server\"}[$__interval]) / 1000",
     "legendFormat": "{{model}}OutputDur"
    }
   ]
  },
  {
   "title": "Queue time / req",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (model,version) ((irate(nv_inference_queue_duration_us{job=\"triton_server\"}[$__rate_interval]) / 1000) / irate(nv_inference_request_success{job=\"triton_server\"}[$__rate_interval]))",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  }
 ]
}