version: "3.9"
services:
  mongo:
    image: mongo
    restart: no
    container_name: edgecv_data_mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ../.temp:/data/db/