name: "P_NMS_PostProcessing"
default_model_filename: "model.py"
platform: "python"
max_batch_size: 16

input [
    {
        name: "output0"
        data_type: TYPE_FP32
        dims: [7, 8400]
    }
]

output [
    {
        name: "boxes"
        data_type: TYPE_FP32
        dims: [-1, 4]
    },
   {
        name: "classes"
        data_type: TYPE_INT32
        dims: [-1]
    },
    {
        name: "scores"
        data_type: TYPE_FP32
        dims: [-1]
    }
]

dynamic_batching {
    preferred_batch_size: [2, 4, 8, 16]
    max_queue_delay_microseconds: 100000
}

parameters {
    key: "max_det",
    value: {string_value: "100"}
}

parameters {
    key: "nms_th",
    value: {string_value: "0.5"}
}

parameters {
    key: "nms_iou_th",
    value: {string_value: "0.75"}
}
